const html5_selectors: string[] = [
    'header',
    'footer',
    'nav li',
    'article',
    'section',
    'aside',
    'main',
    'form',
    'input label datalist option',
    'textarea',
    'button',
    'select option optgroup',
    'fieldset legend',
    'output',
    'ul li',
    'ol li',
    'table thead tbody tr td th caption',
    'a',
    'span',
    'p br',
    'strong',
    'em',
    'i',
    'b',
    'u',
    's',
    'code',
    'var',
    'cite',
    'abbr',
    'time',
    'mark',
    'small',
    'sub',
    'sup',
    'img',
    'audio source',
    'video source track',
    'picture',
    'pre',
    'code',
    'html',
    'head',
    'title',
    'meta',
    'body',
    'iframe',
    'embed',
    'object',
    'param',
    'noscript',
    'script',
    'figure figcaption img',
    'link'
]

export default html5_selectors